Kuweza/Models/Job.cs
using System;

namespace Kuweza.Models
{
    public class Job
    {
        public int JobId { get; set; }
        public string JobNumber { get; set; }
        public int StatusId { get; set; }
        public string TypeOfEquiry { get; set; }
        public bool Quoted { get; set; }
        public DateTime DateReceived { get; set; }
        public string KuwezaQuoteNo { get; set; }
        public string ProofOfEnquiry { get; set; }
        public string MethodOfCommunication { get; set; }
        public string AssignTo { get; set; }
        public int ClientId { get; set; }
        public string UserId { get; set; }     
    }
}

Kuweza/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Kuweza.Models;
using System.IO;

namespace Kuweza.Controllers
{
    public class JobsController : Controller
    {
        private KuwezaContext db = new KuwezaContext();
        SageConnectBase validate = new SageConnectBase();

        // GET: Jobs
        public ActionResult Index()
        {
            return View(db.Jobs.ToList());
        }

        // GET: Jobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: Jobs/Create
        public ActionResult Create()
        {
            ViewBag.UserName = new SelectList(db.Users.ToList(), "UserName", "UserName");
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JobId,JobNumber,StatusId,TypeOfEquiry,Quoted,DateReceived,KuwezaQuoteNo,MethodOfCommunication,AssignTo,ClientId,UserId")] Job job, HttpPostedFileBase file, int id)
        {
            if (ModelState.IsValid)
            {
                Job newjob = new Job
                {
                    DateReceived = DateTime.Today,
                    MethodOfCommunication = job.MethodOfCommunication,
                    TypeOfEquiry = job.TypeOfEquiry,
                    KuwezaQuoteNo = "KQ128020",
                    StatusId = 0,
                    AssignTo = job.AssignTo,
                   // ProofOfEnquiry = job.ProofOfEnquiry,
                    ClientId = id,
                    Quoted = false,
                    UserId = "100500"
                };
                int month = DateTime.Now.Month;
                int year = DateTime.Now.Year;
                int day = DateTime.Now.Day;
                int hour = DateTime.Now.Hour;
                int minute = DateTime.Now.Minute;
                string typ = newjob.TypeOfEquiry.Substring(0,1);
                string jobNum = newjob.ClientId + "-" + typ + "-" + year + month + day + "-" + hour + minute;
                newjob.JobNumber = jobNum;

                if (Request != null)
                {
                        file = Request.Files["EnquiryUpload"];
                        string fileName = file.FileName;                                   
                        string fileContentType = file.ContentType;
                        byte[] fileBytes = new byte[file.ContentLength];
                        file.InputStream.Read(fileBytes, 0, Convert.ToInt32(file.ContentLength));
                        file.SaveAs((Path.Combine(Server.MapPath("~/OrderRequestFiles/"), fileName)));
                        newjob.ProofOfEnquiry = fileName;                  
                }

                db.Jobs.Add(newjob);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(job);
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobId,JobNumber,StatusId,TypeOfEquiry,Quoted,DateReceived,KuwezaQuoteNo,ProofOfEnquiry,MethodOfCommunication,AssignTo,ClientId,UserId")] Job job)
        {
            if (ModelState.IsValid)
            {
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(job);
        }

        // GET: Jobs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public FileResult Download(string fileName)
        {
            return File("~/OrderRequestFiles/" +fileName, System.Net.Mime.MediaTypeNames.Application.Octet);
        }
        public ActionResult ProofOfEnquiry(string fileName)
        {
            return Download(fileName);
        }
        public ActionResult CreateList()
        {
            return View();
        }
       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Kuweza/Views/Jobs/Create.cshtml
@model Kuweza.Models.Job

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Jobs", FormMethod.Post, new { @class = "col s12", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <h4>Job</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.TypeOfEquiry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeOfEquiry", new List<SelectListItem>()
    {
        new SelectListItem() { Text = "Product", Value = "Product" },
        new SelectListItem() { Text = "Service", Value = "Service", Selected = true }
    }, "Select ...")
                @Html.ValidationMessageFor(model => model.TypeOfEquiry, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="row">
            @Html.LabelFor(model => model.ProofOfEnquiry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="input-field col s10">
                @*@Html.EditorFor(model => model.ProofOfEnquiry, new { htmlAttributes = new { @class = "validate" } })
                @Html.ValidationMessageFor(model => model.ProofOfEnquiry, "", new { @class = "text-danger" })
                @Html.LabelFor(model => model.ProofOfEnquiry)*@
                <div class="file-field input-field">
                    <input class="file-path validate" type="text" />
                    <div class="btn">
                        <span>File</span>
                        <input type="file" id="inputFile" name="EnquiryUpload" multiple="" />
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MethodOfCommunication, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MethodOfCommunication", new List<SelectListItem>()
    {
        new SelectListItem() { Text= "Mail", Value = "Mail", Selected = true },
         new SelectListItem() { Text= "Skype", Value = "Skype"  },
          new SelectListItem() { Text= "Facebook", Value = "Facebook"  },
            new SelectListItem() { Text= "Call", Value = "Call"  },
              new SelectListItem() { Text= "SMS", Value = "SMS"  },
            new SelectListItem() { Text= "Visual", Value = "Visual" }
    }, "Select ...")
                @Html.ValidationMessageFor(model => model.MethodOfCommunication, "", new { @class = "text-danger" })
            </div>
        </div>
 
        <div class="form-group">
            @Html.LabelFor(model => model.AssignTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.AssignTo, (IEnumerable<SelectListItem>)ViewBag.UserName)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div> 
        @ViewBag.Message

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kuweza/Views/Jobs/CreateList.cshtml
@model Kuweza.Models.Job

@{
    ViewBag.Title = "CreateList";
}
@{ 
}
<script src="~/Scripts/jquery-2.2.3.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<style>
    .ui-autocomplete {
        cursor: pointer;
        height: 120px;
        overflow-y: scroll;

    }
     .dropdiv {
        width:auto;
        height: 540px;
        padding:10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        background-color:lightblue;
    }
      .deletediv {
        width:auto;
        height: 540px;

        padding:10px;
    }
     .sourcediv {
        width:auto;
        height: 540px;
        padding-bottom:50px;
    }
</style>
<script type="text/javascript">
    $(document).ready(function () {
        // $("#products").load('/Items/AllProducts');
        itemsList();
    })
    function itemsList() {
        $.post("/Items/GetInitialItemList", function (data) {
            $("#products").fadeOut(500);
            $("#products").fadeIn(500);
            $("#products").html(data);
        });
    }
    function allowDrop(ev) {
        ev.preventDefault();
    }
    function drag(ev) {       
        ev.dataTransfer.setData("ID", ev.target.id);
    }
    function dragitem(ev, pid) {
        sessionStorage.setItem('PID', pid);
    }
    function dragstart(event) {
        event.dataTransfer.setData("Text", event.target.textContent);
     
    }
    function drop(ev) {
        var rnd = Math.random() * 50 + 1;
        var data = ev.dataTransfer.getData("Text");
        var productId = sessionStorage.getItem('PID');
        var jobId = "@Url.RequestContext.RouteData.Values["id"]";
        var clientId = "@Request.QueryString["clientid"]";
        $.post("/Products/AddItem", { "ProductName": data, "JobNumber": jobId, "ClientId": clientId, "RandomId":rnd, "SageProductId":productId });
        var lst = $("#lstselectedproducts");
        var li = "<center><font color='#FDFEFE'><h4><li id=" + rnd + " draggable='true' ondragstart='drag(event)'>" + data + " </li></h4></font></center>";
        li.textContent = data;
        lst.append(li);
    }
    function delItem(ev) {
        ev.preventDefault();
        var data = ev.dataTransfer.getData("ID");
        var el = document.getElementById(data);
        el.parentNode.removeChild(el);
        $.post("/Products/DeleteItem", { "RandomID": data });
    }
</script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<font color="#689000"><center><h2>Order #:@Url.RequestContext.RouteData.Values["id"]</h2></center></font>

<script src="~/Scripts/bootstrap.min.js"></script>
<div class="container">
            <div class="row">
                <div class="row col-lg-4 col-md-4">
                    <div class="card darken-1">                     
                        <div class="card-content black-text">
                            <h3>Items List</h3>
                            <hr/>
                            <div id="products" class="sourcediv"></div>
                        </div>
                    </div>
                </div>
                <div class="row col-lg-4 col-md-4">               
                    <div class="card darken-1">
                        
                        <div class="card-content black-text">
                            <h3>Selected Items</h3>
                            <div id="order" class="dropdiv" ondrop="drop(event)" ondragover="allowDrop(event)">
                                <ul id="lstselectedproducts"></ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row col-lg-4 col-md-4">
                    <div class="card darken-1">
                       
                        <div class="card-content black-text">
                            <h3>Drop to delete</h3>
                            <hr />
                            <div id="del" class="deletediv" ondrop="delItem(event)" ondragover="allowDrop(event)"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
}

Kuweza/Views/Jobs/Delete.cshtml
@model Kuweza.Models.Job

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.JobNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeOfEquiry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeOfEquiry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quoted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quoted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateReceived)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateReceived)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KuwezaQuoteNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KuwezaQuoteNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProofOfEnquiry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProofOfEnquiry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MethodOfCommunication)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MethodOfCommunication)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssignTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Kuweza/Views/Jobs/Details.cshtml
@model Kuweza.Models.Job

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.JobNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeOfEquiry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeOfEquiry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quoted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quoted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateReceived)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateReceived)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KuwezaQuoteNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KuwezaQuoteNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProofOfEnquiry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProofOfEnquiry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MethodOfCommunication)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MethodOfCommunication)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssignTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignTo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.JobId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Kuweza/Views/Jobs/Edit.cshtml
@model Kuweza.Models.Job

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Job</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.JobId)

        <div class="form-group">
            @Html.LabelFor(model => model.JobNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StatusId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeOfEquiry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeOfEquiry, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeOfEquiry, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quoted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Quoted)
                    @Html.ValidationMessageFor(model => model.Quoted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateReceived, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateReceived, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateReceived, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KuwezaQuoteNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KuwezaQuoteNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KuwezaQuoteNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProofOfEnquiry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProofOfEnquiry, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProofOfEnquiry, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MethodOfCommunication, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MethodOfCommunication, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MethodOfCommunication, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssignTo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AssignTo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AssignTo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kuweza/Views/Jobs/Index.cshtml
@model IEnumerable<Kuweza.Models.Job>

@{
    ViewBag.Title = "Jobs";
}

<h2>Jobs</h2>

<p>
    @Html.ActionLink("Create New Job", "GetAll", "Customers", null, new { id = 1 })    
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.JobNumber)
        </th>      
        <th>
            @Html.DisplayNameFor(model => model.TypeOfEquiry)
        </th>
      
        <th>
            @Html.DisplayNameFor(model => model.DateReceived)
        </th>
      
        <th>
            @Html.DisplayNameFor(model => model.MethodOfCommunication)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssignTo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClientId)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.JobNumber)
        </td>
     
        <td>
            @Html.DisplayFor(modelItem => item.TypeOfEquiry)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.DateReceived)
        </td>
              
        <td>
            @Html.DisplayFor(modelItem => item.MethodOfCommunication)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AssignTo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClientId)
        </td>
        <td>
            <div class="badge alert-info"> @Html.ActionLink("Download", "ProofOfEnquiry", new { fileName = item.ProofOfEnquiry })</div>|
            <div class="badge alert-info">@Html.ActionLink("Add Items", "CreateList", new { id = item.JobNumber, clientid=item.ClientId })</div>|
            <div class="badge alert-info">@Html.ActionLink("Allocate Suppliers", "Index", "Products", new { id = item.JobNumber, clientid = item.ClientId }, null)</div>|
            <div class="badge alert-info">@Html.ActionLink("Final Quote", "Index", "ItemsToSuppliers", new { id = item.JobNumber, clientid = item.ClientId }, null)</div> |
            <div class="badge alert-info"> @Html.ActionLink("Edit", "Edit", new { id = item.JobId })</div>
</td>
    </tr>
}
</table>