Kuweza/Models/Customer.cs
using System.ComponentModel.DataAnnotations;

namespace Kuweza.Models
{
    public class Customer : BaseModel
    {
        public string Name { get; set; }
        //  public Category Category { get; set; }
      
        // public SalesRepresentative SalesRepresentative { get; set; }
       // public string TaxReference { get; set; }
        public string ContactName { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string WebAddress { get; set; }
        [Display(Name = "Business Reg#")]
        public string BusinessRegistrationNumber { get; set; }
        //  public bool Active { get; set; }
        //  public decimal Balance { get; private set; }
        //   public decimal CreditLimit { get; set; }
        //   public int CommunicationMethod { get; set; }
        [Display(Name = "Postal Address Place")]
        public string PostalAddress01 { get; set; }
        [Display(Name = "Postal Address Street")]
        public string PostalAddress02 { get; set; }
        [Display(Name = "Postal Address City")]
        public string PostalAddress03 { get; set; }
        [Display(Name = "Postal Address Country")]
        public string PostalAddress04 { get; set; }
        [Display(Name = "Postal Address Code")]
        public string PostalAddress05 { get; set; }
        [Display(Name = "Delivery Place")]
        public string DeliveryAddress01 { get; set; }
        [Display(Name = "Delivery Street")]
        public string DeliveryAddress02 { get; set; }
        [Display(Name = "Delivery City")]
        public string DeliveryAddress03 { get; set; }
        [Display(Name = "Delivery Country")]
        public string DeliveryAddress04 { get; set; }
        [Display(Name = "Delivery Area Code")]
        public string DeliveryAddress05 { get; set; }
        public int? SalesRepresentativeId { get; set; }
        [Display(Name = "Category")]
        public string TextField1 { get; set; }
        [Display(Name = "Markup(%)")]
        public string TextField2 { get; set; }
        //     public bool AutoAllocateToOldestInvoice { get; set; }
        //     public bool EnableCustomerZone { get; set; }
        //     public string CustomerZoneGuid { get; private set; }
        //     public bool CashSale { get; set; }
        //     public string TextField1 { get; set; }
        //     public string TextField2 { get; set; }
        //     public string TextField3 { get; set; }
        //     public decimal NumericField1 { get; set; }
        //    public decimal NumericField2 { get; set; }
        //     public decimal NumericField3 { get; set; }
        //     public bool YesNoField1 { get; set; }
        //     public bool YesNoField2 { get; set; }
        //     public bool YesNoField3 { get; set; }
        //     public string DateField1 { get; set; }
        //    public string DateField2 { get; set; }
        //    public string DateField3 { get; set; }
        //     public int DefaultPriceListId { get; set; }
        //  public DefaultPricelist DefaultPriceList { get; set; }
        //     public string DefaultPriceListName { get; set; }
        //      public bool AcceptsElectronicInvoices { get; set; }
        //      public string Modified { get; private set; }
        //      public string Created { get; private set; }

        //       public string TaxStatusVerified { get; set; }
        //     public int CurrencyId { get; set; }
    }
}

Kuweza/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Kuweza.Models;

namespace Kuweza.Controllers
{
    public class CustomersController : Controller
    {
        private KuwezaContext db = new KuwezaContext();
        //Initialising connection to sage. This will check the username, password, api key and company id
        SageConnectBase validate = new SageConnectBase();
        //GET: Customers
        public ActionResult Index()
        {
            var api = new ApiRequest(validate.Username, validate.Password, validate.Apikey, validate.CompanyId);
            var cust = api.CustomerRequest.Get();
            return View(cust.Results);
        }
        //UPDATE: Customers
        public ActionResult Update()
        {
            var api = new ApiRequest(validate.Username, validate.Password, validate.Apikey, validate.CompanyId);
            var cust = api.CustomerRequest.Get();
            return View(cust.Results);
        }
        public ActionResult GetCompanyList()
        {
            var api = new ApiRequest(validate.Username, validate.Password, validate.Apikey, validate.CompanyId);
            List<Customer> allItems = api.CustomerRequest.Get().Results;
            string listItems = "";
            foreach (Customer items in allItems)
            {
                listItems += String.Format("<div class='row' id={0} draggable='true' ondragstart='dragstart(event)' onclick='editCustomer(this.id)' style='cursor:pointer;'>{1}</div>", items.ID, items.Name);
            }
            string data = String.Format(@"{0}", listItems);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        //Ajax call to edit customer
        public ActionResult EditCustomer(int CustomerId)
        {
            var api = new ApiRequest(validate.Username, validate.Password, validate.Apikey, validate.CompanyId);
            var customers = api.CustomerRequest.Get(CustomerId);       
            string data = String.Format(@"<div class='col s12 m12 l12'>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Customer Name</div>
                    <div class='col m6 l6'><input type='text' id='cname' name='cname' value='{0}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Contact Name</div>
                    <div class='col m6 l6'><input type='text' id='contactname' name='contactname' value='{1}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Telephone #</div>
                    <div class='col m6 l6'><input type='text' id='tel' name='tel' value='{2}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Fax #</div>
                    <div class='col m6 l6'><input type='text' id='fax' name='fax' value='{3}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Mobile #</div>
                    <div class='col m6 l6'><input type='text' id='mobile' name='mobile' value={4} /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Email Address</div>
                    <div class='col m6 l6'><input type='text' id='email' name='email' value='{5}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Web Address</div>
                    <div class='col m6 l6'><input type='text' id='webaddress' name='webaddress' value='{6}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Supplier Category</div>
                    <div class='col m6 l6'><input type='text' id='scat' name='scat' value='{7}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Postal Address Place</div>
                    <div class='col m6 l6'><input type='text' id='pap' name='pap' value='{8}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Postal Address City</div>
                    <div class='col m6 l6'><input type='text' id='pac' name='pac' value='{9}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Postal Address Country</div>
                    <div class='col m6 l6'><input type='text' id='pacountry' name='pacountry' value='{10}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Postal Address Code</div>
                    <div class='col m6 l6'><input type='text' id='pacode' name='pacode' value='{11}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Delivery Address Place</div>
                    <div class='col m6 l6'><input type='text' id='dap' name='dap' value='{12}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Delivery Address City</div>
                    <div class='col m6 l6'><input type='text' id='dac' name='dac' value='{13}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Delivery Address Country</div>
                    <div class='col m6 l6'><input type='text' id='dacountry' name='dacountry' value='{14}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Delivery Address Area Code</div>
                    <div class='col m6 l6'><input type='text' id='dacode' name='dacode' value='{15}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Business Reg#</div>
                    <div class='col m6 l6'><input type='text' id='busreg' name='busreg' value='{16}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>Mark Up(%)</div>
                    <div class='col m6 l6'><input type='text' id='markup' name='markup' value='{17}' /></div>
                </div>
                <div class='row'>
                    <div class='col m6 l6' align='left'>&nbsp;</div>
                    <div class='col m6 l6'><input type='button' id='btnsubmit' name='btnsubmit' value='Update Customer' onclick='updateCustomer({18})' /></div>
                </div>
   </div>", customers.Name, customers.ContactName, customers.Telephone, customers.Fax, customers.Mobile, customers.Email, customers.WebAddress, customers.TextField1, customers.PostalAddress01, customers.PostalAddress03, customers.PostalAddress04, customers.PostalAddress05, customers.DeliveryAddress01, customers.DeliveryAddress03, customers.DeliveryAddress04, customers.DeliveryAddress05, customers.BusinessRegistrationNumber, customers.TextField2, customers.ID);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        //Ajax delete customer
        public ActionResult DeleteCustomer(int CustomerId)
        {
            var api = new ApiRequest(validate.Username, validate.Password, validate.Apikey, validate.CompanyId); ;
            var result = api.CustomerRequest.Delete(CustomerId);
            return null;
        }
        //Ajax add supplier
        public ActionResult AddCustomer(string CustomerName, string ContactName, string Tel, string Fax, string Mobile, string Email, string WebAddress, string SupplierCat, string DaCity, string DaCode, string DaPlace, string DaCountry, string PaCity, string PaCode, string PaPlace, string PaCountry, string BusReg, string MarkUp)
        {
            var api = new ApiRequest(validate.Username, validate.Password, validate.Apikey, validate.CompanyId);
            var cust = new Customer
            {
                Name = CustomerName,
                Fax = Fax,
                Mobile = Mobile,
                Email = Email,
                WebAddress = WebAddress,
                ContactName = ContactName,
                DeliveryAddress01 = DaPlace,
                DeliveryAddress03 = DaCity,
                DeliveryAddress04 = DaCountry,
                DeliveryAddress05 = DaCode,
                PostalAddress01 = PaPlace,
                PostalAddress03 = PaCity,
                PostalAddress04 = PaCountry,
                PostalAddress05 = PaCode,
                BusinessRegistrationNumber = BusReg,
                TextField1 = SupplierCat,
                TextField2 = MarkUp,
                Telephone = Tel
            };
            api.CustomerRequest.Save(cust);
            return null;
        }
        //Ajax update customer
        public ActionResult UpdateCustomer(int ID, string CustomerName, string ContactName, string Tel, string Fax, string Mobile, string Email, string WebAddress, string SupplierCat, string DaCity, string DaCode, string DaPlace, string DaCountry, string PaCity, string PaCode, string PaPlace, string PaCountry, string BusReg, string MarkUp)
        {
            var api = new ApiRequest(validate.Username, validate.Password, validate.Apikey, validate.CompanyId);
            var cust = api.CustomerRequest.Get(ID);
            cust.Name = CustomerName;
            cust.Fax = Fax;
            cust.Mobile = Mobile;
            cust.Email = Email;
            cust.WebAddress = WebAddress;
            cust.ContactName = ContactName;
            cust.DeliveryAddress01 = DaPlace;
            cust.DeliveryAddress03 = DaCity;
            cust.DeliveryAddress04 = DaCountry;
            cust.DeliveryAddress05 = DaCode;

Kuweza/Views/Customers/Create.cshtml
@model Kuweza.Models.Customer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


<script src="~/Scripts/jquery-2.2.3.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<link href="~/Content/msgbox.css" rel="stylesheet">


<!-- The Modal -->
<div id="myMessage" class="msg">
    <!-- MsgBox content -->
    <div class="msg-content">
        <div class="msg-header">
            <span class="close">×</span>
            <h3>Message</h3>
            <hr />
        </div>
        <br /><p></p>
        <div class="msg-body" id="msgContent">

        </div>
        <p>
        </p>
    </div>
</div>

<div class="col s12 m12 l12">
    <center>
        <div class="card darken-1" style="width:60%;">
            <div class="card-content black-text">
                <span class="card-title" style="color:black" id="supplierName"><strong>Create New Customer</strong></span>
                <p>&nbsp;</p>
                <div class="row">
                    <div class="col-lg-6" align="left">Customer Name</div>
                    <div class="col-lg-6"><input type="text" id="cname" name="cname" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Contact Name</div>
                    <div class="col-lg-6"><input type="text" id="contactname" name="contactname" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Telephone #</div>
                    <div class="col-lg-6"><input type="text" id="tel" name="tel" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Fax #</div>
                    <div class="col-lg-6"><input type="text" id="fax" name="fax" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Mobile #</div>
                    <div class="col-lg-6"><input type="text" id="mobile" name="mobile" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Email Address</div>
                    <div class="col-lg-6"><input type="text" id="email" name="email" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Web Address</div>
                    <div class="col-lg-6"><input type="text" id="webaddress" name="webaddress" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Supplier Category</div>
                    <div class="col-lg-6"><input type="text" id="scat" name="scat" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Postal Address Place</div>
                    <div class="col-lg-6"><input type="text" id="pap" name="pap" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Postal Address City</div>
                    <div class="col-lg-6"><input type="text" id="pac" name="pac" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Postal Address Country</div>
                    <div class="col-lg-6"><input type="text" id="pacountry" name="pacountry" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Postal Address Code</div>
                    <div class="col-lg-6"><input type="text" id="pacode" name="pacode" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Delivery Address Place</div>
                    <div class="col-lg-6"><input type="text" id="dap" name="dap" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Delivery Address City</div>
                    <div class="col-lg-6"><input type="text" id="dac" name="dac" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Delivery Address Country</div>
                    <div class="col-lg-6"><input type="text" id="dacountry" name="dacountry" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Delivery Address Area Code</div>
                    <div class="col-lg-6"><input type="text" id="dacode" name="dacode" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Business Reg#</div>
                    <div class="col-lg-6"><input type="text" id="busreg" name="busreg" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">Mark Up (%)</div>
                    <div class="col-lg-6"><input type="text" id="markup" name="markup" value="" /></div>
                </div>
                <div class="row">
                    <div class="col-lg-6" align="left">&nbsp;</div>
                    <div class="col-lg-6"><input type="button" id="btnsubmit" name="btnsubmit" value="Create Customer" /></div>
                </div>
            </div>
        </div>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
    </center>
</div>
<script type="text/javascript">
 $(document).ready(function () {
     //  some code to show the form is getting ready
 });
     var message = document.getElementById('msgContent');
     var msgframe = document.getElementById('myMessage');
     var span = document.getElementsByClassName("close")[0];
     //Setting action listerners
     // When the user clicks on <span> (x), close the message
     span.onclick = function () {
         msgframe.style.display = "none";
     }
     // When the user clicks anywhere outside of the modal, close it
     window.onclick = function (event) {
         if (event.target == msgframe) {
             msgframe.style.display = "none";
         }
     }
     $('#btnsubmit').click(function () {
        var customerName = document.getElementById('cname').value;
        var contactName = document.getElementById('contactname').value;
        var tel = document.getElementById('tel').value;
        var fax = document.getElementById('fax').value;
        var mobile = document.getElementById('mobile').value;
        var email = document.getElementById('email').value;
        var webAddress = document.getElementById('webaddress').value;
        var supplierCat = document.getElementById('scat').value;
        var paCity = document.getElementById('pac').value;
        var paPlace = document.getElementById('pap').value;
        var paCode = document.getElementById('pacode').value;
        var paCountry = document.getElementById('pacountry').value;
        var daCity = document.getElementById('dac').value;
        var daPlace = document.getElementById('dap').value;
        var daCode = document.getElementById('dacode').value;
        var daCountry = document.getElementById('dacountry').value;
        var busReg = document.getElementById('busreg').value;
        var markUp = document.getElementById('markup').value;
        // Validation input using javascript

        if ((/^\s*$/).test(customerName)) {
            message.textContent = "Enter customer name";
            msgframe.style.display = "block";
        }
        else
        if ((/^\s*$/).test(email)) {
            message.textContent = "Enter email ";
            msgframe.style.display = "block";
        }
        else
        if ((/^\s*$/).test(busReg)) {
            message.textContent = "Enter business registration number";
            msgframe.style.display = "block";
        }
        else
            if ((/^\s*$/).test(markUp)) {
                message.textContent = "Markup percentage is required";
                msgframe.style.display = "block";
            }
        else
            //Now lets call ajax post to insert our values
        {
                $.post("/Customers/AddCustomer", {
                    "CustomerName": customerName,
                    "ContactName": contactName,
                    "Tel": tel, "Fax": fax,
                    "Mobile": mobile,
                    "Email": email,
                    "WebAddress": webAddress,
                    "SupplierCat": supplierCat,
                    "DaCity": daCity,
                    "DaCode": daCode,
                    "DaPlace": daPlace,
                    "DaCountry": daCountry,
                    "PaCity": paCity,
                    "PaCode": paCode,
                    "PaPlace": paPlace,
                    "PaCountry": paCountry,
                    "BusReg": busReg,
                    "MarkUp": markUp
                },
                function (response, status) { // Required Callback Function
                    if (status == "success") {
                        message.textContent = "Customer created successfully";
                        msgframe.style.display = "block";
                    }
                    else {
                        message.textContent = "Error: " + response;
                        msgframe.style.display = "block";
                    }
                }
                );         
        }
    });
</script>

Kuweza/Views/Customers/Delete.cshtml
@model Kuweza.Models.Customer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BusinessRegistrationNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BusinessRegistrationNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalAddress01)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalAddress01)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalAddress02)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalAddress02)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalAddress03)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalAddress03)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalAddress04)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalAddress04)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalAddress05)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalAddress05)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryAddress01)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryAddress01)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryAddress02)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryAddress02)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryAddress03)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryAddress03)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryAddress04)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryAddress04)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryAddress05)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryAddress05)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SalesRepresentativeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SalesRepresentativeId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Kuweza/Views/Customers/GetAll.cshtml
@model IEnumerable<Kuweza.Models.Customer>

@{
    ViewBag.Title = "Add New Job";
}

<h2>Add New Job</h2>

<p>
    @Html.ActionLink("Create New Customer", "Create", "Customers", null, new { id = 1 }) &nbsp; | &nbsp;@Html.ActionLink("Job List", "Index", "Jobs", null, new { id = 1 })
    
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telephone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fax)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mobile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WebAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BusinessRegistrationNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TextField1)
        </th>
           <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContactName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telephone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fax)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mobile)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WebAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BusinessRegistrationNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TextField1)
        </td>
        <td>
            @Html.ActionLink("Create Job", "Create", "Jobs", new { id=item.ID }, null) |
          
        </td>
    </tr>
}

</table>